---
- name: Create local iobroker executable
  template:
    src: iobroker-cmd.j2
    dest: "{{iob_dir}}/iobroker"
    owner: "{{iob_user}}"
    group: "{{iob_group}}"
    mode: 0775
  become: true

- name: "Get information about {{iob_dir}}/iob"
  stat:
    path: "{{iob_dir}}/iob"
  register: iob_file
  become: true

- name: "Remove {{iob_dir}}/iob if it is a regular file"
  file:
    state: absent
    path: "{{iob_dir}}/iob"
    owner: "{{iob_user}}"
    group: "{{iob_group}}"
    mode: 0777
  become: true
  when: iob_file.stat.isreg | bool

- name: Create local iob executable
  file:
    state: link
    src: "{{iob_dir}}/iobroker"
    path: "{{iob_dir}}/iob"
    owner: "{{iob_user}}"
    group: "{{iob_group}}"
    mode: 0777
  become: true

- name: Create global iobroker executables
  file:
    state: link
    src: "{{iob_dir}}/iobroker"
    path: "{{item}}"
    owner: "root"
    group: "root"
    mode: 0777
  become: true
  with_items: "{{iob_cmd_links}}"

- name: "Make sure {{ansible_user_dir}}/.iobroker folder exists"
  file:
    state: directory
    path: "{{ansible_user_dir}}/.iobroker"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0775
  become: true

- name: Setup CLI completions
  copy:
    src: iobroker_completions
    dest: "{{ansible_user_dir}}/.iobroker/iobroker_completions"
    owner: "root"
    group: "root"
    mode: 0644
  become: true

- name: Setup NPM command fix
  template:
    src: npm-command-fix.j2
    dest: "{{ansible_user_dir}}/.iobroker/npm_command_fix"
    owner: "root"
    group: "root"
    mode: 0644
  become: true

- name: Start iobroker
  service:
    name: "{{iob_service}}"
    enabled: true
    state: started
  become: true

- name: Execute post install commands
  shell:
    cmd: "{{item.command}}"
  become: "{{item.execute_as_root}}"
  with_items: "{{iob_post_install_commands}}"
